train:
  _target_: src.datasets.LJSpeechDataset
  part: "train"
  data_dir: "/kaggle/input/the-lj-speech-dataset/LJSpeech-1.1"
test:
  _target_: src.datasets.LJSpeechDataset
  part: "test"
  data_dir: "/kaggle/input/the-lj-speech-dataset/LJSpeech-1.1"